project_id = "tanfumztvxgtrbrnfkkk"

[auth]
site_url = "https://mirroraigallery.com"
additional_redirect_urls = [
  "https://mirroraigallery.com/**",
  "https://www.mirroraigallery.com/**",
  "https://moment-reflections-suite.lovable.app/**",
  "https://046b0b4a-a0ce-426a-85c8-d3989700a2de.lovableproject.com/**",
  "https://id-preview--046b0b4a-a0ce-426a-85c8-d3989700a2de.lovable.app/**"
]

[functions.upload-to-r2]
verify_jwt = false

[functions.face-recognition]
verify_jwt = false

[functions.detect-face]
verify_jwt = false

[functions.notify-guests]
verify_jwt = false