import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}"
  ],
  prefix: "",
  theme: {
    spacing: {
      0: "0", px: "1px", 0.5: "2px", 1: "4px", 2: "8px",
      3: "12px", 4: "16px", 5: "20px", 6: "24px", 7: "28px",
      8: "32px", 9: "36px", 10: "40px", 11: "44px", 12: "48px",
      14: "56px", 16: "64px", 20: "80px", 24: "96px",
    },
    borderRadius: {
      none: "0",
      DEFAULT: "0",
      sharp: "0",
      sm: "0",
      soft: "0",
      md: "0",
      rounded: "0",
      lg: "0",
      xl: "0",
      "2xl": "0",
      "3xl": "0",
      pill: "999px",
      full: "999px",
    },
    boxShadow: {
      none: "none",
      DEFAULT: "var(--shadow-border)",
      border: "var(--shadow-border)",
      lift: "var(--shadow-lift)",
      float: "var(--shadow-float)",
      modal: "var(--shadow-modal)",
      sm: "var(--shadow-border)",
      md: "var(--shadow-lift)",
      lg: "var(--shadow-float)",
      xl: "var(--shadow-modal)",
      "2xl": "var(--shadow-modal)",
      inner: "var(--shadow-border)",
    },
    container: {
      center: true,
      padding: "20px",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        sans: ['"DM Sans"', 'system-ui', 'sans-serif'],
        display: ['"Cormorant Garamond"', 'Georgia', 'serif'],
        serif: ['"Cormorant Garamond"', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        "2xs": ["10px", { lineHeight: "1.4" }],
        xs:   ["11px", { lineHeight: "1.4" }],
        sm:   ["12px", { lineHeight: "1.5" }],
        base: ["14px", { lineHeight: "1.55" }],
        md:   ["16px", { lineHeight: "1.5" }],
        lg:   ["18px", { lineHeight: "1.3" }],
        xl:   ["24px", { lineHeight: "1.15", letterSpacing: "-0.01em" }],
        "2xl":["32px", { lineHeight: "1.1",  letterSpacing: "-0.01em" }],
        "3xl":["44px", { lineHeight: "1.05", letterSpacing: "-0.015em" }],
        "4xl":["56px", { lineHeight: "1.0",  letterSpacing: "-0.02em" }],
      },
      colors: {
        ivory:   '#FAFAF8',
        noir:    '#0E0D0B',
        ink:     '#111111',
        gold:    '#B8953F',
        grid: {
          noir: '#000000',
          surface: '#111111',
          elevated: '#1a1a1a',
          border: '#222222',
          'border-muted': '#333333',
          gold: '#B8953F',
          ivory: '#FFFFFF',
          muted: '#666666',
          hint: '#444444',
        },
        canvas:  '#F5F0E8',
        surface: '#EEEBE4',
        muted2:  '#6B6860',
        success: '#7C9A6B',
        error:   '#A8615B',
        border: "hsl(var(--border))",
        input:  "hsl(var(--input))",
        ring:   "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      transitionTimingFunction: {
        "v2-press": "cubic-bezier(0.4,0,0.2,1)",
        "v2-spring": "cubic-bezier(0.32,0.72,0,1)",
      },
      transitionDuration: {
        instant: "80ms", fast: "160ms", base: "240ms", slow: "340ms",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(4px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "skeleton-pulse": {
          "0%, 100%": { opacity: "0.5" },
          "50%": { opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out forwards",
        "skeleton-pulse": "skeleton-pulse 1200ms ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
