INSERT INTO website_templates (slug, label, description, category, font_family, ui_font_family, bg_color, text_color, text_secondary_color, nav_bg, nav_border, header_style, hero_style, card_bg, footer_bg, footer_text_color, is_active, sort_order, styling_config, section_config, demo_content)
VALUES
-- 1) Clean Minimal
(
  'clean-minimal',
  'Clean Minimal',
  'Light, airy portfolio with elegant serif typography and generous whitespace',
  'wedding',
  '"Playfair Display", Georgia, serif',
  '"Inter", sans-serif',
  '#FFFFFF',
  '#1A1A1A',
  '#6B6B6B',
  'rgba(255,255,255,0.95)',
  'rgba(0,0,0,0.06)',
  'solid',
  'editorial',
  '#FAFAFA',
  '#FFFFFF',
  '#999999',
  true,
  6,
  '{"buttonStyle":"outline","spacing":"generous","galleryColumnsDesktop":3,"galleryColumnsTablet":2,"galleryColumnsMobile":1}'::jsonb,
  '{"sections":[{"id":"hero","enabled":true,"order":0},{"id":"social","enabled":true,"order":1},{"id":"portfolio","enabled":true,"order":2},{"id":"about","enabled":true,"order":3},{"id":"testimonials","enabled":true,"order":4},{"id":"journal","enabled":true,"order":5},{"id":"inquiry","enabled":true,"order":6},{"id":"contact","enabled":true,"order":7},{"id":"footer","enabled":true,"order":8}]}'::jsonb,
  '{"hero":{"headline":"Timeless Photography","tagline":"Capturing life''s most beautiful moments with grace and intention","button_text":"Explore Portfolio"},"about":{"bio":"I believe in the quiet power of a photograph — a single frame that holds the warmth of a glance, the tenderness of a touch, the joy of a fleeting second. My approach is unhurried, intentional, and deeply personal."},"portfolio":{"layout":"grid","max_images":12},"contact":{"heading":"Let''s Create Together","button_text":"Send Inquiry","show_whatsapp":false},"footer":{"text":"© 2026 Studio Name. Crafted with care.","show_social":true},"services":[{"title":"Wedding Coverage","description":"Full day documentary storytelling","icon":"camera"},{"title":"Portrait Sessions","description":"Intimate studio & outdoor portraits","icon":"people"},{"title":"Engagement Stories","description":"Pre-wedding love stories","icon":"heart"}],"testimonials":[{"name":"Priya & Arjun","text":"Every photo feels like a poem. We couldn''t have asked for a more thoughtful photographer.","location":"Mumbai"},{"name":"Sarah & James","text":"The way our story was captured was nothing short of magical. Pure artistry.","location":"Goa"}]}'::jsonb
),
-- 2) Magazine Editorial
(
  'magazine-editorial',
  'Magazine Editorial',
  'Bold fashion-inspired layout with asymmetric grids and strong typography',
  'wedding',
  '"Bodoni Moda", "Didot", serif',
  '"Syne", sans-serif',
  '#0F0F0F',
  '#EDEDED',
  '#888888',
  'rgba(15,15,15,0.85)',
  'rgba(255,255,255,0.08)',
  'transparent',
  'editorial',
  '#1A1A1A',
  '#0A0A0A',
  '#666666',
  true,
  7,
  '{"buttonStyle":"solid","spacing":"editorial","galleryColumnsDesktop":2,"galleryColumnsTablet":2,"galleryColumnsMobile":1}'::jsonb,
  '{"sections":[{"id":"hero","enabled":true,"order":0},{"id":"featured_galleries","enabled":true,"order":1},{"id":"portfolio","enabled":true,"order":2},{"id":"storytelling","enabled":true,"order":3},{"id":"about","enabled":true,"order":4},{"id":"testimonials","enabled":true,"order":5},{"id":"journal","enabled":true,"order":6},{"id":"inquiry","enabled":true,"order":7},{"id":"contact","enabled":true,"order":8},{"id":"footer","enabled":true,"order":9}]}'::jsonb,
  '{"hero":{"headline":"THE ART OF SEEING","tagline":"Editorial Wedding & Fashion Photography","button_text":"View Work"},"about":{"bio":"My work lives at the intersection of fine art and photojournalism. I approach every shoot as a creative collaboration — bold, editorial, and unapologetically artistic."},"portfolio":{"layout":"masonry","max_images":16},"contact":{"heading":"Commission a Story","button_text":"Get in Touch","show_whatsapp":false},"footer":{"text":"© 2026 Studio. All rights reserved.","show_social":true},"featured_stories":[{"title":"Eternal Frames","location":"Udaipur","image_url":""},{"title":"Golden Hour","location":"Jaipur","image_url":""},{"title":"Velvet Dreams","location":"Paris","image_url":""}],"services":[{"title":"Editorial Weddings","description":"Magazine-worthy coverage with cinematic vision","icon":"camera"},{"title":"Fashion Portraits","description":"Bold, high-fashion editorial sessions","icon":"star"},{"title":"Brand Campaigns","description":"Visual storytelling for luxury brands","icon":"briefcase"}],"testimonials":[{"name":"Meera & Vikram","text":"Our wedding photos look like they belong in a fashion magazine. Absolutely stunning editorial eye.","location":"Udaipur"},{"name":"Ananya & Rohan","text":"Every frame is a work of art. The boldness and creativity blew us away.","location":"Delhi"}]}'::jsonb
),
-- 3) Warm & Organic
(
  'warm-organic',
  'Warm & Organic',
  'Earthy tones with soft typography and an intimate, romantic atmosphere',
  'wedding',
  '"Lora", Georgia, serif',
  '"Nunito Sans", sans-serif',
  '#FAF6F1',
  '#3D3228',
  '#8B7D6B',
  'rgba(250,246,241,0.95)',
  'rgba(61,50,40,0.08)',
  'solid',
  'editorial',
  '#F5EFE8',
  '#3D3228',
  '#A69882',
  true,
  8,
  '{"buttonStyle":"rounded","spacing":"cozy","galleryColumnsDesktop":3,"galleryColumnsTablet":2,"galleryColumnsMobile":1}'::jsonb,
  '{"sections":[{"id":"hero","enabled":true,"order":0},{"id":"social","enabled":true,"order":1},{"id":"portfolio","enabled":true,"order":2},{"id":"about","enabled":true,"order":3},{"id":"services","enabled":true,"order":4},{"id":"testimonials","enabled":true,"order":5},{"id":"journal","enabled":true,"order":6},{"id":"newsletter","enabled":true,"order":7},{"id":"inquiry","enabled":true,"order":8},{"id":"contact","enabled":true,"order":9},{"id":"footer","enabled":true,"order":10}]}'::jsonb,
  '{"hero":{"headline":"Love, Naturally","tagline":"Warm, heartfelt photography for couples who value authenticity","button_text":"See Our Stories"},"about":{"bio":"I''m drawn to the unscripted — the quiet glances, the spontaneous laughter, the tender moments that make your story uniquely yours. My style is warm, organic, and deeply rooted in connection."},"portfolio":{"layout":"grid","max_images":12},"contact":{"heading":"Tell Me Your Story","button_text":"Say Hello","show_whatsapp":true},"footer":{"text":"© 2026 Studio Name. Made with love.","show_social":true},"services":[{"title":"Intimate Weddings","description":"Small, heartfelt celebrations captured with warmth","icon":"heart"},{"title":"Couples Sessions","description":"Relaxed, natural sessions in golden light","icon":"sun"},{"title":"Family Stories","description":"Authentic moments of connection and joy","icon":"people"}],"testimonials":[{"name":"Riya & Karan","text":"The warmth in our photos is exactly how the day felt. It''s like reliving the emotions all over again.","location":"Kerala"},{"name":"Tara & Nikhil","text":"So natural, so real. Every photo radiates warmth and love. Couldn''t be happier.","location":"Coorg"}]}'::jsonb
);