
-- SEO landing pages auto-generated by AI
CREATE TABLE public.seo_pages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  meta_description TEXT,
  heading TEXT,
  body_html TEXT,
  keywords TEXT[] DEFAULT '{}',
  location TEXT,
  page_type TEXT NOT NULL DEFAULT 'landing',
  status TEXT NOT NULL DEFAULT 'draft',
  views INTEGER DEFAULT 0,
  leads_captured INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, slug)
);

ALTER TABLE public.seo_pages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own SEO pages"
  ON public.seo_pages FOR ALL TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Public can view published SEO pages"
  ON public.seo_pages FOR SELECT TO anon
  USING (status = 'published');

-- Trigger for updated_at
CREATE TRIGGER seo_pages_updated_at
  BEFORE UPDATE ON public.seo_pages
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
